const products = [
    {
      name: 'Hay',
      price: '£4.50',
      stock: 1,
      link: '',
      image: '/products/hay.jpg',
      alt: 'Hay',
    },
    {
      name: 'Straw',
      price: '£4.00',
      stock: 1,
      link: '',
      image: '/products/straw.jpg',
      alt: 'Straw',
    },
    {
      name: 'Haylage',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/haylage.jpg',
      alt: 'Haylage',
    },
    {
      name: 'Kindling',
      price: '£6.00',
      stock: 2,
      link: '',
      image: '/products/kindling.jpg',
      alt: 'Kindling',
    },
    {
      name: 'Small logs',
      price: '£7.00',
      stock: 2,
      link: '',
      image: '/products/small-log.jpg',
      alt: 'Small log',
    },
    {
      name: 'Eggs',
      price: '£2.50 (6 units)',
      stock: 1,
      link: '',
      image: '/products/eggs.jpg',
      alt: 'Eggs',
    },
    {
      name: 'Fertilised eggs',
      price: '£12.00 (6 units)',
      stock: 1,
      link: '',
      image: '/products/fertilised-egg.jpg',
      alt: 'Fertilised eggs',
    },
    {
      name: 'Day old ducklings/chicks',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/duckling-chick.jpg',
      alt: 'Day old ducklings/chicks',
    },
    {
      name: 'Young Waterfowl',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/young-waterfowl.jpg',
      alt: 'Young Waterfowl',
    },
    {
      name: 'Apples',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/apples.jpg',
      alt: 'Apples',
    },
    {
      name: 'Pears',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/pears.jpg',
      alt: 'Pears',
    },
    {
      name: 'Gages, plums, damsons',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/plums.jpg',
      alt: 'Gages, plums, damsons',
    },
    {
      name: 'Cherries',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/cherries.jpg',
      alt: 'Cherries',
    },
    {
      name: 'Nuts',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/nuts.jpg',
      alt: 'Nuts',
    },
    {
      name: 'Hedgerow fruit',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/hedgerow-fruits.jpg',
      alt: 'Hedgerow fruit',
    },
    {
      name: 'British saanen goats cheese',
      price: 'Contact us',
      stock: 3,
      link: '/contact',
      image: '/products/goat-cheese.jpg',
      alt: 'British saanen goats cheese',
    },
  ];
  
  export default products;  